# Creating a playbook that calls other task in other playbook
---
- name: Conditions part2
  hosts: web
  become: true
  remote_user: root
  tasks:
    - name: check the file existence.
      stat: path=/var/www/html/index.html
      register: stat_output

    - name: show the ouput of above variable
      debug: var=stat_output

    - name: create the index file if not present
      copy:
        dest: /var/www/html/index.html
        content: "This is condition contents"
      when: stat_output.stat.exists==false
...
